### ISSUE TITLE
[BUG] after patch 1.5 (palworld)

### ISSUE THREAD

**Issue by kokiwixx** [KOOKIIEStudios/PalCON-Discord#23]
This script will now launch the program.
Please select the environment to run the source code with:
A: Virtual Python Environment (Default)
B: Global Python Environment
What is your choice [A,B]?A
You have selected A: Virtual Python Environment
2024-02-29 15:44:03,628 - client - DEBUG - Fetching logger for client
2024-02-29 15:44:03,629 - client - INFO - Fetching configuration file
2024-02-29 15:44:03,630 - __main__ - DEBUG - Fetching logger for __main__
2024-02-29 15:44:03,671 - client - INFO - Setting up RCON connection
2024-02-29 15:44:03,671 - client - DEBUG - Fetching online players
2024-02-29 15:44:05,711 - __main__ - ERROR - Error updating bot status: [WinError 10061] No connection could be established because the target computer expressly refused it

**Comment by Korefox** [comment]
This is not an issue with the PalCON-discord bot, and there is a workaround for this issue to get RCON working again in v1.5.0.

The palworld devs broke RCON functionality in v1.5.0. The cause is due to the server no longer referencing the `PalWorldSettings.ini` file when setting the RCON port.

In Palworld v1.5.0, you need to add a new command line argument when starting the server. The CLI argument is: `-RCONPort=25575` where the 25575 integer is whatever port you configured your RCON bot to talk with.

In some instances, you may also need to add the CLI argument `-RCONEnabled=True` along with the above argument.

If you are in the official Palworld discord server, I made a post about how to fix it in the palworld dedicated-server-help channel:
https://discord.com/channels/505994577942151180/1200387813317812304/1211875662395088986

- In the palworld discord server, a palworld network developer has also made a statement about the issue here. https://discord.com/channels/505994577942151180/1200387813317812304/1211967049333473330

- This issue is also reportedly fixed in Palworld v1.5.1, the you may refer to the official patch notes at:
https://store.steampowered.com/news/app/1623730/view/4122553433962552821?l=english

or in the discord announcements section at:
https://discord.com/channels/505994577942151180/855784007722598451/1212572464589312001
"・Fixed an issue where the settings to enable RCON were not loaded from the configuration file"

**Comment by kokiwixx** [comment]
tks

**Comment by Bratah123** [comment]
Thanks for the catch, and the provided workarounds!
